Filmoteka/Models/ViewModels/MyLibrary.cs
#nullable disable
namespace Filmoteka.Models.ViewModels
{
    public class MyLibrary
    {
        public int GenreId { get; set; }
        public ICollection<Movie> MovieList { get; set; } = new List<Movie>();
        public ICollection<Series> SeriesList { get; set; } = new List<Series>();
        public ICollection<Movie> MoviesML { get; set; } = new List<Movie>();
        public ICollection<Series> SeriesML { get; set; } = new List<Series>();
        public string movieSearch { get; set; }
        public ICollection<User> NickMovie { get; set; } = new List<User>();
        public ICollection<User> NickSeries { get; set; } = new List<User>();
    }
}

Filmoteka/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Filmoteka.Data;
using Filmoteka.Models;
using Filmoteka.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Newtonsoft.Json;
using TMDbLib.Client;

namespace Filmoteka.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _environment;
        private readonly UserManager<User> _userManager;

        public MoviesController(ApplicationDbContext context, IWebHostEnvironment environment, UserManager<User> userManager)
        {
            _context = context;
            _environment = environment;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
              return View(_context.Movies.ToList());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Movies == null)
            {
                return NotFound();
            }

            TempData["id"] = id;
            var UserId = _userManager.GetUserId(User);
            var movie = await _context.Movies.FirstOrDefaultAsync(m => m.Id == id);
            var movieGenreComment = new MovieGenreCommentsViewModel();

            movieGenreComment.Movie = movie;

            var movieGenre = _context.MovieSeriesGenres.Where(x => x.MovieId == id).ToList();

            movieGenre.ForEach(mg =>
            {
                movieGenreComment.Genres.Add(_context.Genres.Where(g => g.Id == mg.GenreId).FirstOrDefault());
            });

            var movieComment = _context.Comments.Where(x => x.MovieId == id).ToList();

            movieGenreComment.Comments = movieComment;

            var ifRated = _context.Ratings.Where(x => x.UserId == UserId && x.MovieId == id).FirstOrDefault();

            if (ifRated != null)
            {
                TempData["Rate"] = ifRated.Rate; 
            }

            //pobieranie ocen z bazy
            var movieRateCount = _context.Ratings.Where(x => x.MovieId == id).ToList().Count;
            if (movieRateCount > 0)
            {
                movie.Avg = (float)_context.Ratings.Where(x => x.MovieId == id).Select(s => s.Rate).Average();
            }
            movie.AvgCount = movieRateCount;

            //oceny z api
            TMDbClient client = new TMDbClient("07ccb68af3750babdf2c2b47d75369c6");
            var responseMovie2 = client.SearchMovieAsync(movie.Title).Result.Results;
            if (responseMovie2.Count != 0)
            {
                var responseMovie = client.SearchMovieAsync(movie.Title).Result.Results[0];
                movie.TMDBRate = (float)responseMovie.VoteAverage;
                movie.TMDBRateCount = responseMovie.VoteCount;
                movie.TMDBlink = $"https://www.themoviedb.org/movie/{responseMovie.Id}";

            } else {
                ViewBag.TMDBError = true;
            }

            movieGenreComment.Links = _context.Links.Where(x => x.MovieId == id).ToList();
            movieGenreComment.MoviesML = _context.Movies.Where(x => x.UserId == UserId).ToList();
            movieGenreComment.SeriesML = _context.Series.Where(x => x.UserId == UserId).ToList();

            if (movie == null)
            {
                return NotFound();
            }

            return View(movieGenreComment);
        }

        [Authorize]
        public IActionResult Create()
        {
            var movieGenreComment = new MovieGenreCommentsViewModel();
            var UserId = _userManager.GetUserId(User);

            ViewBag.GenreId = new SelectList(_context.Genres, "Id", "Name");
            movieGenreComment.MoviesML = _context.Movies.Where(x => x.UserId == UserId).ToList();
            movieGenreComment.SeriesML = _context.Series.Where(x => x.UserId == UserId).ToList();
            return View(movieGenreComment);
        }
 
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Director,RelaseDate,Description,Video,MovieSeriesGenreId,Image")] Movie movie)
        {
            var UserId = _userManager.GetUserId(User);

            if (movie.Image != null)
            { 
                if (!movie.Video.Contains("https://www.youtube.com/watch?v") || movie.Video.Length < 43 || movie.Video.Length > 46)
                {
                    ViewData["ErrorVideo"] = "Link do filmu jest nieprawidłowy";
                    ViewBag.GenreId = new SelectList(_context.Genres, "Id", "Name");
                    return View(movie);
                }
                if (ModelState.IsValid)
                {
                    movie.UserId = UserId;
                    movie.Photo = "";
                    movie.Video = convertLinkToVideo(movie.Video);
                    _context.Add(movie);
                    await _context.SaveChangesAsync();

                    UploadMainPhoto(movie);
                    if (movie.Image == null)
                    {
                        _context.Remove(movie);
                        _context.SaveChanges();

                        var tmpMovie = new MovieGenreCommentsViewModel();
                        tmpMovie.Movie = movie;

                        ViewBag.GenreId = new SelectList(_context.Genres, "Id", "Name");
                        return View(tmpMovie);
                    }
                    movie.Photo = $"/img/films/{movie.Id}.jpg";
                    _context.Movies.Update(movie);

                    movie.MovieSeriesGenreId.ToList().ForEach(x =>
                    {
                        var NewMovie = new MovieSeriesGenre()
                        {
                            MovieId = movie.Id,
                            GenreId = Convert.ToInt32(x)
                        };
                        _context.Add(NewMovie);
                    });
                    await _context.SaveChangesAsync();

                    return Redirect("/Home/Films");
                }
            }
            else
            {
                ViewData["ErrorImage"] = "Pole Dodaj zdjęcie jest wymagane";
            }
          
            ViewBag.GenreId = new SelectList(_context.Genres, "Id", "Name");
            return View(movie);
        }


        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddRate(MovieGenreCommentsViewModel test, int id)
        {
            var rate = new Rating();
            rate.MovieId = id;
            rate.Rate = test.Rate;
            rate.UserId = _userManager.GetUserId(User);

            _context.Add(rate);
            _context.SaveChanges();

            return RedirectToAction("Details", new { id });
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateComment(int? id, [Bind("Description")] Comment comment)
        {
            if (id == null || _context.Movies == null)
            {
                return NotFound();
            }

            TempData["id"] = id;
            var user = await _userManager.GetUserAsync(User);

            
            
            comment.Name = user.NickName;
            comment.MovieId = id;
            comment.DateTime = DateTime.Now;
            _context.Add(comment);
            await _context.SaveChangesAsync();
            
            return RedirectToAction("Details", new { id });
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddLinkToMovie(int? id, [Bind("Name","Quality","URL")] Link link)
        {
            if (id == null || _context.Movies == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);

            link.Username = user.NickName;
            link.MovieId = id;

            _context.Add(link);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", new { id });

            /*  if (link.URL.Contains("vidoza") || link.URL.Contains("upstream"))
              {


                      _context.Add(link);
                      await _context.SaveChangesAsync();
                      return RedirectToAction("Details", new { id });

              } 
              else 
              {
                  return RedirectToAction("Details", new { id });
              }*/

        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Movies == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Director,RelaseDate,Description,Photo,Video,MovieSeriesGenreId")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        public async Task<IActionResult> Delete(int? id)

Filmoteka/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Filmoteka</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.0/chart.min.js" integrity="sha512-sW/w8s4RWTdFFSduOTGtk4isV1+190E/GghVffMA9XczdJ2MDzSzLEubKAs5h0wzgSJOQTRYyaz73L3d6RtJSg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Filmoteka.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-dark navbar-expand-md navbar-toggleable-md border-bottom box-shadow mb-3 fixed-top" style="background-color: #0d0d0d; border-top: 0px; border-color: goldenrod !important;">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Filmoteka</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-md-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Strona główna</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Films">Filmy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Series">Seriale</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial">
                </div>
            </div>
        </nav>
    </header>
    <partial name="_MyLibrary">

    <div class="container">
        <main role="main" class="pb-3 marginTop">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color: #0d0d0d; border-top: 0px; border-color: goldenrod !important;">
        <div class="container">
            &copy; 2022 - Filmoteka - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Filmoteka/Views/Shared/_MyLibrary.cshtml
@if (this.User.Identity.IsAuthenticated)
{
    <div class="offcanvas offcanvas-start text-white" style="background-color: #212529;" tabindex="-1" id="offcanvasWithBackdrop" aria-labelledby="offcanvasWithBackdropLabel">
        <div class="offcanvas-header">
            <h3 class="offcanvas-title" id="offcanvasWithBackdropLabel">Moja biblioteka</h3>
            <button type="button" class="btn-close btn-close-white text-reset"  data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            <h5>Moje filmy</h5>
            <hr>
            @if (Model.MoviesML.Count == 0)
            {
                <p>Brak dodanych filmów</p>
            }
            else
            {
                @foreach (var element in Model.MoviesML)
                {
                    <p><a class="text-decoration-none" style="color: goldenrod;" asp-controller="Movies" asp-action="Details" asp-route-id="@element.Id">@element.Title</a> <span class="text-muted">@element.DateTime.ToString("dd/MM/yyyy")</span></p>
                }
            }

            <h5 class="mt-5">Moje seriale</h5>
            <hr>
            @if (Model.SeriesML.Count == 0)
            {
                <p>Brak dodanych seriali</p>
            }
            else
            {
                @foreach (var element in Model.SeriesML)
                {
                    <p><a class="text-decoration-none" style="color: goldenrod;" asp-controller="Series" asp-action="Details" asp-route-id="@element.Id">@element.Title</a> <span class="text-muted">@element.DateTime.ToString("dd/MM/yyyy")</span></p>
                }
            }
        </div>
    </div>
}